apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  serviceAccountName: loki-service-account
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: storage-loki-0
  containers:
  - name: ubuntu
    image: arfanpantua/monitoring-installer:1.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true;do cd /home; curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip;unzip awscliv2.zip; ./aws/install; sleep 24h;done"] 
    volumeMounts:
      - mountPath: "/home"
        name: pv-storage
  restartPolicy: Always